spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true                        # SQL 쿼리 로깅
    generate-ddl: true                    # DDL 자동 생성
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # 데이터베이스 초기화 지연

  cache:
    type: redis

  datasource:
    url: jdbc:mysql://localhost:3306/concert?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: testuser
    password: 1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: redis-container
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1